---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: node-healthcheck-selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: node-healthcheck-webhook-cert
spec:
  secretName: node-healthcheck-webhook-cert
  issuerRef:
    kind: Issuer
    name: node-healthcheck-selfsigned
  dnsNames:
    - node-healthcheck-webhook-service.kube-system.svc
    - node-healthcheck-webhook-service.kube-system.svc.cluster.local
