---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: database-critical
value: 1200
globalDefault: false
preemptionPolicy: PreemptLowerPriority
description: "Stateful data services"
