---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: external-facing
value: 500
globalDefault: false
preemptionPolicy: PreemptLowerPriority
description: "Public-facing services"
