---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: internal-only
value: 100
globalDefault: false
preemptionPolicy: PreemptLowerPriority
description: "Internal tools and services"
