---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: network-critical
value: 1750
globalDefault: false
preemptionPolicy: PreemptLowerPriority
description: "Network and ingress infrastructure"
