---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: storage-critical
value: 2000
globalDefault: false
preemptionPolicy: PreemptLowerPriority
description: "Storage infrastructure"
