---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vanilla-config
data:
  ops.json: |
    [
      {
        "name": "zebernst",
        "level": 4,
        "bypassesPlayerLimit": true
      }
    ]
  whitelist.json: |
    [
      { "name": "zebernst" },
      { "name": "Travler34_RVA" },
      { "name": "Snorlocke" }
    ]
