apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vanilla
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: vanilla-secret
    template:
      data:
        RCON_PASSWORD: "{{ .RCON_PASSWORD }}"
  dataFrom:
    - extract:
        key: minecraft
