---
endpoints:
  - name: vanilla
    group: minecraft
    url: "tcp://vanilla.games.svc.cluster.local:25565"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    ui:
      hide-url: true
      hide-hostname: true
      hide-port: true
    alerts:
      - type: pushover
