# yaml-language-server: $schema=https://json.schemastore.org/kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - externalsecret.yaml
  - helmrelease.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: vanilla-config
    files:
      - configs/ops.json
      - configs/whitelist.json
  - name: vanilla-bluemap-config
    files:
      - bluemap/core.conf
      - bluemap/webapp.conf
      - bluemap/webserver.conf
