# yaml-language-server: $schema=https://json.schemastore.org/kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - externalsecret.yaml
  - helmrelease.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: vanilla-bluemap-config
    files:
      - bluemap/core.conf
      - bluemap/webapp.conf
      - bluemap/webserver.conf
  - name: vanilla-gatus-ep
    files:
      - config.yaml=gatus-config.yaml
    options:
      labels:
        gatus.io/enabled: "true"
