# yaml-language-server: $schema=https://json.schemastore.org/kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
configMapGenerator:
  - name: mc-router-gatus-ep
    files:
      - config.yaml=gatus-config.yaml
    options:
      labels:
        gatus.io/enabled: "true"
