---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/clusterexternalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: ghcr-pull-secret
spec:
  namespaceSelectors:
    - matchLabels: {} # all namespaces
  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: onepassword
    target:
      name: ghcr-pull-secret
      template:
        type: kubernetes.io/dockerconfigjson
        data:
          .dockerconfigjson: |
            {"auths":{"ghcr.io":{"auth":"{{ printf "%s:%s" .GITHUB_USERNAME .GITHUB_TOKEN | b64enc }}"}}}
    dataFrom:
      - extract:
          key: ghcr.io
