---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: ${APP}
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
spec:
  endpoints:
    - dnsName: "${APP}.zebernst.dev"
      recordType: CNAME
      targets: ["mc.zebernst.dev"]
