apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: atm10
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: atm10-secret
    template:
      data:
        RCON_PASSWORD: "{{ .RCON_PASSWORD }}"
        CF_API_KEY: "{{ .CF_API_KEY }}"
  dataFrom:
    - extract:
        key: minecraft
    - extract:
        key: curseforge
