---
global:
  priorityClassName: control-plane-critical
crds:
  enabled: true
extraArgs:
  - --enable-gateway-api
replicaCount: 1
dns01RecursiveNameservers: https://1.1.1.1:443/dns-query,https://1.0.0.1:443/dns-query
dns01RecursiveNameserversOnly: true
prometheus:
  enabled: true
  servicemonitor:
    enabled: true
