---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unwrapped
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: unwrapped-secret
    template:
      engineVersion: v2
      data:
        secrets.toml: |
          [connections.nocodb]
          dialect = "postgresql"
          host = "redspot-rw.database.svc.cluster.local"
          port = 5432
          database = "nocodb"
          username = "{{ .NOCODB_POSTGRES_USER }}"
          password = "{{ .NOCODB_POSTGRES_PASS }}"

          [connections.nocodb.create_engine_kwargs]
          pool_size = 20
          max_overflow = 30
          pool_pre_ping = true
          pool_recycle = 300

          [connections.nocodb.create_engine_kwargs.connect_args]
          options = "-c search_path={{ .UNWRAPPED_NOCODB_SCHEMA }}"
  dataFrom:
    - extract:
        key: nocodb
    - extract:
        key: unwrapped
