---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: step-issuer-provisioner
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: step-issuer-provisioner-secret
    template:
      data:
        password: "{{ .password }}"
  dataFrom:
    - extract:
        key: tinyca-step-issuer
