---
apiVersion: certmanager.step.sm/v1beta1
kind: StepClusterIssuer
metadata:
  name: tinyca-internal
spec:
  url: https://tinyca.internal
  caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJsakNDQVQyZ0F3SUJBZ0lRV0hZUU4yYnBwa1JyQnZ6QkxqNWt0VEFLQmdncWhrak9QUVFEQWpBcU1ROHcKRFFZRFZRUUtFd1pVYVc1NVEwRXhGekFWQmdOVkJBTVREbFJwYm5sRFFTQlNiMjkwSUVOQk1CNFhEVEkxTVRBdwpNekl6TVRNek5Wb1hEVE0xTVRBd01USXpNVE16TlZvd0tqRVBNQTBHQTFVRUNoTUdWR2x1ZVVOQk1SY3dGUVlEClZRUURFdzVVYVc1NVEwRWdVbTl2ZENCRFFUQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJJK2EKMUlOVW5ESzU1QlVnaXY3dUs0NnFNZXg4K0ZvMDFTZWU5U0w4aTdRSXU3c3JRdWNuOGZQTzFjWUszbnBhUFZYSgptZDZSRXNQNVU4bUhidGFWdlNxalJUQkRNQTRHQTFVZER3RUIvd1FFQXdJQkJqQVNCZ05WSFJNQkFmOEVDREFHCkFRSC9BZ0VCTUIwR0ExVWREZ1FXQkJRVmpsNEZDQ2dQKzJRMjdUR00xOWN2YnR6ZVFUQUtCZ2dxaGtqT1BRUUQKQWdOSEFEQkVBaUJPMXVPL2VOWXhpOHNnVFNxRWw2bGx1VnU2NnZJTC9XRWEwcWROTXZuNzVBSWdIWTIrKzdZTgorZklCOThFcm1GazY4UnVuRjJ3Tm96UVo3TTVtL3FBYUkwYz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
  provisioner:
    name: step-issuer
    kid: umOlKT2eKJ_ayEE_lJiKWvkRLH_L6CUqs-ui0T1e9aM
    passwordRef:
      name: step-issuer-provisioner-secret
      namespace: cert-manager
      key: password
